kind: Deployment
apiVersion: apps/v1
metadata:
  name: custom-config-app
  namespace: odm-sandbox
  labels:
    app: custom-config-app
    app.kubernetes.io/component: custom-config-app
    app.kubernetes.io/instance: custom-config-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: custom-config-app
  template:
    metadata:
      labels:
        run: custom-config-app
    spec:
      volumes:
        - name: custom-volume
          persistentVolumeClaim:
            claimName: custom-pvc
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /
              port: custom-port
              scheme: HTTPS
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 45
          terminationMessagePath: /dev/termination-log
          name: websphere-liberty
          livenessProbe:
            httpGet:
              path: /
              port: custom-port
              scheme: HTTPS
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
          ports:
            - name: custom-port
              containerPort: 9443
              protocol: TCP
            - containerPort: 1883
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: custom-volume
              mountPath: /custom_config
          terminationMessagePolicy: File
          image: 'icr.io/appcafe/websphere-liberty:25.0.0.11-full-java17-openj9-ubi'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
